#!/bin/sh
set -e -u -o pipefail

CreateTunnelAdapter(){
   if [ ! -d "/dev/net" ]; then echo "$(date '+%c') Creating network device classification in /dev"; mkdir /dev/net; fi
   if [ ! -c "/dev/net/tun" ]; then
      echo "$(date '+%c') Creating VPN tunnel adapter"
      mknod -m 0666 /dev/net/tun c 10 200
   fi
}

ConfigureAuthentication(){
    if [ -n "$OPENVPN_FILE" ]; then
        set -- "$@" '--config' "${CONFIGDIR}/config/${OPENVPN_FILE}"
    else
        echo "No OpenVPN config found in ${CONFIGDIR}/config/${OPENVPN_FILE}. Exiting."
        exit 1
    fi
    echo "$(date '+%c') WARNING: Authentication file, ${CONFIGDIR}/auth.conf, does not exist - creating"
    if [ ! -z "${OPENVPN_USERNAME}" ] && [ ! -z "${OPENVPN_PASSWORD}" ]; then
        echo "$(date '+%c') Creating authentication file from OPENVPN_USERNAME and OPENVPN_PASSWORD variables"
        echo "${OPENVPN_USERNAME}" > "${CONFIGDIR}/auth.conf"
        echo "${OPENVPN_PASSWORD}" >> "${CONFIGDIR}/auth.conf"
        chmod 600 "${CONFIGDIR}/auth.conf"
        set -- "$@" '--auth-user-pass' 'auth.conf'
    else
        if [ -z "${OPENVPN_USERNAME}" ]; then echo "$(date '+%c') ERROR:   OPENVPN_USERNAME not set, connot continue"; exit 1; fi
        if [ -z "${OPENVPN_PASSWORD}" ]; then echo "$(date '+%c') ERROR:   OPENVPN_PASSWORD not set, connot continue"; exit 1; fi
    fi
    openvpn "$@"
}

echo "$(date '+%c') ***** Starting OpenVPN + HTTP Proxy container *****"
CreateTunnelAdapter
ConfigureAuthentication
