#!/bin/sh
set -e -u -o pipefail

cd /app/ovpn/config/ovpn_tcp

if [ -n "$NORDVPN_CONFIG" ]; then
  set -- "$@" '--config' "${NORDVPN_CONFIG}.nordvpn.com.tcp.ovpn"
else
  echo "No OpenVPN config found in `pwd`/${NORDVPN_CONFIG}.nordvpn.com.tcp.ovpn. Exiting."
  exit 1
fi
if [ -n "$OPENVPN_USERNAME" -a -n "$OPENVPN_PASSWORD" ]; then
  echo "$OPENVPN_USERNAME" > auth.conf
  echo "$OPENVPN_PASSWORD" >> auth.conf
  chmod 600 auth.conf
  set -- "$@" '--auth-user-pass' 'auth.conf'
else
  echo "OpenVPN credentials not set. Exiting."
  exit 1
fi

openvpn "$@"
