version: '2.1'

# Remember:
# export DOCKER_OPTS="--iptables=false"

networks:
  vpn-vlan:
    name: vpn-vlan

services:
  chrome:
    build:
      context: .
      dockerfile: chrome.dockerfile
    networks:
      - vpn-vlan
    cap_add:
      - NET_ADMIN # Needed for UFW outbound rules
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - haproxy
    environment:
      USE_CHROME_STABLE: 'true'
      # Only outgoing port 5000 is exposed
      HTTP_PROXY: "http://haproxy:5000"
      HTTPS_PROXY: "http://haproxy:5000"
      DEFAULT_LAUNCH_ARGS: "[ \"--proxy-server=http://haproxy:5000\" ]"

  haproxy:
    build:
      context: .
      dockerfile: haproxy.dockerfile
    networks:
      - vpn-vlan
    ports:
      - "${PROXY_PORT:-8888}:5000"
      - "${STATS_PORT:-8887}:1936"
    expose:
      - 5000
      - 1936
    restart: always
    depends_on:
      - vpn-proxy
    environment:
      FRONTEND_PORT: 5000
      FRONTEND_MODE: "http"
      BACKENDS: "vpn-proxy"
      BACKENDS_PORT: 8118
      BACKENDS_MODE: "http"
      DNS_ENABLED: "true"
      PROXY_PROTOCOL_ENABLED: "false"
      BALANCE: "source" # roundrobin
      LOG_LEVEL: "debug"

  vpn-proxy:
    build:
      context: .
      dockerfile: vpn-proxy.dockerfile
    cap_add:
      - NET_ADMIN # Needed for VPN tunnel adapter
    dns:
      - "${DNS_SERVER_1:-9.9.9.9}"
      - "${DNS_SERVER_2:-1.1.1.1}"
    environment:
      OPENVPN_USERNAME: "${OPENVPN_USERNAME}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
      OPENVPN_PROVIDER: "${OPENVPN_PROVIDER:-nordvpn}"
      OPENVPN_FILE:     "${OPENVPN_FILE:-ca120.nordvpn.com.tcp.ovpn}"
      LOCAL_NETWORK:    "${LOCAL_NETWORK:-192.168.1.0/24}"
    expose:
      - 8118
    restart: always
    networks:
      - vpn-vlan