name: CI
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        env:
          IMAGE_NAME: vpn-proxy
          GITHUB_USER: sgama
          TOKEN: ${{ secrets.TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
        run: |
          echo 'CI Job Start'
          echo 'DockerHub Registry Login'
          docker login -u $DOCKERHUB_USER --password-stdin <<< "${{ secrets.DOCKERHUB_KEY }}"
          echo 'Github Package Registry Login'
          docker login docker.pkg.github.com -u $GITHUB_USER --password-stdin <<< "${{ secrets.TOKEN }}"
          echo 'Docker Build...'
          docker build . --tag $DOCKERHUB_USER/$IMAGE_NAME:latest
          docker tag $DOCKERHUB_USER/$IMAGE_NAME:latest docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest
          echo 'Pushing Image to Dockerhub ...'
          docker push $DOCKERHUB_USER/$IMAGE_NAME:latest
          echo 'Pushing Image to Github ...'
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest
          echo 'CI Job Complete'